version: "3"

services:

  registry:
    image: registry:2
    ports:
      - 5000:5000
    # environment:
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./data:/var/lib/registry
      # - /path/certs:/certs
      # - /path/auth:/auth
    restart: always

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8888:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
#      ENV_REGISTRY_PROXY_FQDN: reg.my-domain.com
#      ENV_REGISTRY_PROXY_PORT: 443
    restart: always