version: "3"

services:

  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - ./data:/var/lib/registry
    restart: always

  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - 8888:80
    environment:
      ENV_DOCKER_REGISTRY_HOST: registry
      ENV_DOCKER_REGISTRY_PORT: 5000
    restart: always